name: Docker Image CI - Testing

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy to EC2 TEST
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST3_DNS }}  # Asegúrate de que este sea el DNS público de tu instancia EC2
        username: ec2-user                
        key: ${{ secrets.EC2_SSH_KEY }}     
        port: 22                           
        script: |
          echo "Probando conectividad al DNS público"
          ping -c 4 ${{ secrets.HOST3_DNS }} || exit 1  # Verifica que el DNS sea resolvible

          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker pull meybili/ec2-practica:latest
          docker run -d -p 80:80 meybili/ec2-practica:latest

    - name: Deploy to EC2 TO INSTANCE 2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST4_DNS }}  # Asegúrate de que este sea el DNS público de tu instancia EC2
        username: ec2-user                
        key: ${{ secrets.EC2_SSH_KEY }}     
        port: 22                           
        script: |
          echo "Probando conectividad al DNS público"
          ping -c 4 ${{ secrets.HOST4_DNS }} || exit 1  # Verifica que el DNS sea resolvible

          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker pull meybili/ec2-practica:latest
          docker run -d -p 80:80 meybili/ec2-practica:latest