name: Docker Image CI - Testing

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: meybili/ec2-practica:latest

    - name: Deploy to Testing EC2 Instances
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.TEST_HOSTNAME }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Actualizando instancias de pruebas"
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -a -q) || true
          docker pull meybili/ec2-practica:latest
          docker run -d -p 80:80 meybili/ec2-practica:latest
