name: Deploy to EC2 on master branch push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Actualiza Docker en la instancia
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -aG docker $USER
          
          # Autenticación en Docker Hub (opcional si necesitas acceder a imágenes privadas)
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Detiene cualquier contenedor en ejecución (si los hay)
          docker stop $(docker ps -q) || true
          
          # Elimina contenedores antiguos
          docker rm $(docker ps -a -q) || true
          
          # Descarga la imagen actualizada desde Docker Hub
          docker pull meybili/ec2-practica:latest
          
          # Inicia el contenedor en el puerto 80
          docker run -d -p 80:80 meybili/ec2-practica:latest
