name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: meybili/ec2-practica:latest

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i <(echo "$EC2_KEY") ec2-user@3.80.70.22 "
        docker pull meybili/ec2-practica:latest &&
        docker stop \$(docker ps -q) &&
        docker run -d -p 80:80 meybili/ec2-practica:latest
        "
      env:
        EC2_KEY: ${{ secrets.EC2_KEY }}
