name: Docker Image CI - Production

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: meybili/ec2-practica:latest

    - name: Deploy to Auto Scaling Group (ASG)
      run: |
        # Actualizar todas las instancias del Auto Scaling Group
        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name "AutoScalingDocker" \
          --desired-capacity 0  # Detenemos las instancias para que se reinicien con la nueva imagen

        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name "AutoScalingDocker" \
          --desired-capacity 2  # Reiniciamos el Auto Scaling Group con 2 instancias nuevas

        # Esto actualizará las instancias automáticamente con la nueva imagen

